### ISSUE TITLE
instance not closed

### ISSUE THREAD

**Issue by aad1995** [Akmal-CloudFreed/CloudFreed-CloudFlare-bypass#2]
Hello. When I run the example.js, it bypasses Cloudflare well, but the problem is that it remains in the Solving phase and instance.Close() is not run.

**Comment by under4eg** [comment]
For some reason close condition is not working since response doesn't return 'cf_clearance' cookie even though it's present in browser. 
`if (JSON.stringify(ConvertToCDPHeaders(response.params.request.headers)).includes("cf_clearance"))`

You have to somehow change WebSocketManager and add ` websocket.send(JSON.stringify({
                  sessionId: response.sessionId,
                  id: 6,
                  method: 'Network.getAllCookies'
                }));` to another place in order to be able to get all cookies.

Also it doesn't work with capcha where you need to click. Clicker is not triggering because there is no "challenge-stage" in the response body.
